export const stableTaskRewardVaultAddress = (process.env.NEXT_PUBLIC_STABLE_TASK_VAULT_ADDRESS ??
  '0x0000000000000000000000000000000000000000') as `0x${string}`

export const stableTaskRewardVaultAbi = [
  {
    type: 'function',
    stateMutability: 'view',
    name: 'rewardToken',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
  },
  {
    type: 'function',
    stateMutability: 'view',
    name: 'publicTaskCreationFee',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    stateMutability: 'view',
    name: 'nextTaskId',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    name: 'createTask',
    inputs: [
      { name: 'taskType', type: 'uint8' },
      { name: 'pointReward', type: 'uint256' },
      { name: 'rewardAmount', type: 'uint256' },
      { name: 'metadataURI', type: 'string' },
    ],
    outputs: [{ name: 'taskId', type: 'uint256' }],
  },
  {
    type: 'function',
    stateMutability: 'payable',
    name: 'createPublicTask',
    inputs: [
      { name: 'taskType', type: 'uint8' },
      { name: 'pointReward', type: 'uint256' },
      { name: 'rewardAmount', type: 'uint256' },
      { name: 'metadataURI', type: 'string' },
    ],
    outputs: [{ name: 'taskId', type: 'uint256' }],
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    name: 'markTaskCompleted',
    inputs: [
      { name: 'taskId', type: 'uint256' },
      { name: 'user', type: 'address' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    name: 'selfCompleteTask',
    inputs: [{ name: 'taskId', type: 'uint256' }],
    outputs: [],
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    name: 'checkInDailyTask',
    inputs: [{ name: 'taskId', type: 'uint256' }],
    outputs: [],
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    name: 'claimTaskPoint',
    inputs: [{ name: 'taskId', type: 'uint256' }],
    outputs: [],
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    name: 'claimReward',
    inputs: [
      { name: 'taskId', type: 'uint256' },
      { name: 'user', type: 'address' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    stateMutability: 'view',
    name: 'tasks',
    inputs: [{ name: 'taskId', type: 'uint256' }],
    outputs: [
      { name: 'id', type: 'uint256' },
      { name: 'taskType', type: 'uint8' },
      { name: 'creator', type: 'address' },
      { name: 'pointReward', type: 'uint256' },
      { name: 'rewardAmount', type: 'uint256' },
      { name: 'active', type: 'bool' },
      { name: 'publicCreated', type: 'bool' },
      { name: 'metadataURI', type: 'string' },
    ],
  },
  {
    type: 'function',
    stateMutability: 'view',
    name: 'isCompleted',
    inputs: [
      { name: 'taskId', type: 'uint256' },
      { name: 'user', type: 'address' },
    ],
    outputs: [{ name: '', type: 'bool' }],
  },
  {
    type: 'function',
    stateMutability: 'view',
    name: 'hasClaimedReward',
    inputs: [
      { name: 'taskId', type: 'uint256' },
      { name: 'user', type: 'address' },
    ],
    outputs: [{ name: '', type: 'bool' }],
  },
  {
    type: 'function',
    stateMutability: 'view',
    name: 'hasClaimedPoint',
    inputs: [
      { name: 'taskId', type: 'uint256' },
      { name: 'user', type: 'address' },
    ],
    outputs: [{ name: '', type: 'bool' }],
  },
  {
    type: 'event',
    anonymous: false,
    name: 'TaskCreated',
    inputs: [
      { indexed: true, name: 'taskId', type: 'uint256' },
      { indexed: true, name: 'taskType', type: 'uint8' },
      { indexed: true, name: 'creator', type: 'address' },
      { indexed: false, name: 'pointReward', type: 'uint256' },
      { indexed: false, name: 'rewardAmount', type: 'uint256' },
      { indexed: false, name: 'publicCreated', type: 'bool' },
      { indexed: false, name: 'metadataURI', type: 'string' },
    ],
  },
  {
    type: 'event',
    anonymous: false,
    name: 'TaskCompleted',
    inputs: [
      { indexed: true, name: 'taskId', type: 'uint256' },
      { indexed: true, name: 'user', type: 'address' },
      { indexed: true, name: 'operator', type: 'address' },
    ],
  },
  {
    type: 'event',
    anonymous: false,
    name: 'PointClaimed',
    inputs: [
      { indexed: true, name: 'taskId', type: 'uint256' },
      { indexed: true, name: 'user', type: 'address' },
      { indexed: false, name: 'amount', type: 'uint256' },
    ],
  },
  {
    type: 'event',
    anonymous: false,
    name: 'RewardClaimed',
    inputs: [
      { indexed: true, name: 'taskId', type: 'uint256' },
      { indexed: true, name: 'user', type: 'address' },
      { indexed: true, name: 'rewardToken', type: 'address' },
      { indexed: false, name: 'rewardAmount', type: 'uint256' },
    ],
  },
] as const
